Resources:
  EC2II9LP:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0d5bf08bc8017c83b
      InstanceType: t2.micro
      KeyName: ohioaccesskey
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup



  
# Resources: 
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: AllowEC2Traffic
      GroupDescription: Enable SSH access and HTTP access on the inbound port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0



  
    