Resources:
  myGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: devops
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess



  IAMU45U76:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: IAMtestcloud
      
      LoginProfile:
        Password: Arjit$123
        PasswordResetRequired: true
      Path: '/'
      Groups: 
          - devops